version: "3.9"

services:
  backend:
    build: ./Backend
    container_name: Backend
    ports:
      - "3000:3000"
    networks:
      - fleetlinknet
    environment:
      - mongodb+srv://vickysonaiya0189_db_user:0XIrsTYChVTKtWAP@truckmanagement.lcqx4cn.mongodb.net/?retryWrites=true&w=majority&appName=TruckManagement

  frontend:
    build: ./Frontend
    container_name: Frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - fleetlinknet

networks:
  fleetlinknet:
    driver: bridge
